'use strict';

const { app, BrowserWindow, ipcMain, Menu, Tray, nativeImage, Notification, globalShortcut, powerMonitor, screen, shell } = require('electron');
const path = require('node:path');
const fs = require('node:fs');
const { pathToFileURL } = require('node:url');
const { execFile } = require('node:child_process');
const { ReminderStore, validateNotification, readJson, writeJson } = require('./reminders.cjs');

// Keep the original profile path and app identity so a display-name change does
// not make existing local calendars appear to disappear.
app.setPath('userData', path.join(app.getPath('appData'), '拾日'));
app.setName('昱时');
app.setAppUserModelId('app.shiri.calendar');
// Opt-in development-only smoke mode never displays a window or touches the shell.
// Its profile is isolated from real calendar data and remains under the task workspace.
const smokeTest = !app.isPackaged && process.env.SHIRI_SMOKE_TEST === '1';
if (smokeTest) app.setPath('userData', path.resolve(__dirname, '..', '..', '..', 'work', 'desktop-smoke-profile'));
const desktopDiagnostic = !app.isPackaged && process.env.SHIRI_DESKTOP_DIAGNOSTIC === '1';
if (desktopDiagnostic) app.setPath('userData', path.resolve(__dirname, '..', '..', '..', 'work', 'desktop-diagnostic-profile'));
const hasLock = app.requestSingleInstanceLock();
if (!hasLock) app.quit();

const entryFile = path.join(__dirname, '..', 'dist', 'index.html');
const entryUrl = pathToFileURL(entryFile).href;
let developmentUrl = null;
if (!app.isPackaged && process.env.SHIRI_DEV_URL) {
  const candidate = new URL(process.env.SHIRI_DEV_URL);
  if (candidate.protocol !== 'http:' || !['localhost', '127.0.0.1', '[::1]'].includes(candidate.hostname)) {
    throw new Error('SHIRI_DEV_URL must be a local http URL.');
  }
  developmentUrl = candidate.href;
}

// Multi-size "日历对勾" icon generated by scripts/desktop-icon.mjs.
// macOS cannot read .ico; the Dock icon comes from the bundle's .icns instead.
const appIconPath = path.join(__dirname, process.platform === 'darwin' ? 'icon-256.png' : 'icon.ico');
const loginItemSupported = process.platform === 'win32' || process.platform === 'darwin';
const CELL_EDITOR_TITLE = '昱时 · 格内编辑';
const CELL_EDITOR_MIN_WIDTH = 180;
const CELL_EDITOR_COMPACT_HEIGHT = 204;
const CELL_EDITOR_EXPANDED_HEIGHT = 382;

let mainWindow = null;
let desktopWindow = null;
const editorWindows = new Set();
// One focusable cell editor is created in advance and reused, so a double-click
// only moves and reveals it instead of starting a new renderer each time.
let cellEditorWindow = null;
let cellEditorLoading = null;
let cellEditorAnchor = null;
let cellEditorExpanded = false;
let cellEditorRevealPending = false;
let cellEditorRevealTimer = null;
// Numbers each open request so a late close from the previous date is ignored.
let cellEditorSeq = 0;
// Reminder popup in the lower-right corner, with "remind again in 10 minutes".
const reminderFile = path.join(__dirname, 'reminder.html');
const reminderUrl = pathToFileURL(reminderFile).href;
const SNOOZE_MINUTES = 10;
let reminderWindow = null;
let reminderLoading = null;
let reminderShown = [];
let tray = null;
let quitting = false;
let recreating = false;
let mode = 'window';
let nativeState = null;
let desktopHost = null;
let calendarInteractive = false;
let shortcutRegistered = false;
let lastError = null;
let settings = { opacity: 1, autostart: false, startupMode: 'desktop', widgetSpan: 'twoWeeks', widgetSide: 'right' };
let settingsFile;
let reminders;
let reminderTimer;
let modeQueue = Promise.resolve();
let lastImmediateNotification = 0;
const visibleNotifications = new Set();

function resolveStartupMode(savedMode, platform = process.platform, hiddenTest = smokeTest) {
  if (hiddenTest) return 'window';
  // The Windows launcher is the desktop calendar. Older releases persisted
  // "window" after a temporary mode switch, which made the next launch look
  // like a conventional application instead of the requested desktop surface.
  if (platform === 'win32') return 'desktop';
  const preferred = ['window', 'desktop', 'fullscreen'].includes(savedMode) ? savedMode : 'desktop';
  return preferred === 'desktop' && platform !== 'win32' ? 'window' : preferred;
}

function errorMessage(error) {
  return typeof error?.message === 'string' ? error.message.slice(0, 700) : String(error).slice(0, 700);
}

function helperPath() {
  // electron-builder must unpack desktop.ps1 because Windows PowerShell cannot read ASAR.
  const unpacked = path.join(process.resourcesPath, 'app.asar.unpacked', 'desktop', 'desktop.ps1');
  return app.isPackaged && fs.existsSync(unpacked) ? unpacked : path.join(__dirname, 'desktop.ps1');
}

function nativeHandle(window) {
  const handle = window.getNativeWindowHandle();
  return handle.length >= 8 ? handle.readBigUInt64LE(0).toString() : String(handle.readUInt32LE(0));
}

function widgetRect() {
  const work = screen.getPrimaryDisplay().workArea;
  // Electron uses DIP, while the Explorer helper uses physical screen pixels.
  return screen.dipToScreenRect(null, work);
}

function setCalendarInteractive(interactive) {
  if (!desktopWindow || desktopWindow.isDestroyed() || !nativeState) return false;
  if (calendarInteractive !== interactive) {
    desktopWindow.setIgnoreMouseEvents(!interactive, interactive ? undefined : { forward: true });
    calendarInteractive = interactive;
  }
  return true;
}

// The calendar page tracks whether it asked for mouse input. Whenever the main
// process changes that state on its own, the page must forget its cached value;
// otherwise it never asks again and every later click falls through to Explorer.
function resetDesktopPointer() {
  setCalendarInteractive(false);
  if (desktopWindow && !desktopWindow.isDestroyed() && !desktopWindow.webContents.isDestroyed()) {
    desktopWindow.webContents.send('desktop:pointer-reset');
  }
}

function callDesktopHelper(action, state, rect) {
  if (process.platform !== 'win32') return Promise.reject(new Error('桌面常驻模式目前仅支持 Windows。'));
  if (!desktopWindow || desktopWindow.isDestroyed()) return Promise.reject(new Error('桌面日历窗口已关闭。'));
  const powershell = path.join(process.env.SystemRoot || 'C:\\Windows', 'System32', 'WindowsPowerShell', 'v1.0', 'powershell.exe');
  const args = ['-NoLogo', '-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', helperPath(),
    '-Action', action, '-Hwnd', nativeHandle(desktopWindow), '-OwnerProcessId', String(process.pid), '-Opacity', String(settings.opacity)];
  if (state) args.push('-StateBase64', Buffer.from(JSON.stringify(state), 'utf8').toString('base64'));
  if (rect) args.push('-Left', String(rect.x), '-Top', String(rect.y), '-Width', String(rect.width), '-Height', String(rect.height));
  return new Promise((resolve, reject) => {
    execFile(powershell, args, { windowsHide: true, timeout: 12_000, maxBuffer: 64 * 1024, encoding: 'utf8' }, (error, stdout, stderr) => {
      let result;
      try { result = JSON.parse(stdout.trim().replace(/^\uFEFF/, '')); } catch { /* handled below */ }
      if (result?.ok) return resolve(result);
      const failure = new Error(result?.error || (error?.killed ? '桌面连接超时，已恢复普通窗口。' : stderr.trim() || errorMessage(error || '桌面连接失败。')));
      failure.restoreState = result?.state;
      failure.rollbackError = result?.rollbackError;
      failure.uncertain = !result;
      reject(failure);
    });
  });
}

function snapshot(surface = 'app') {
  return {
    mode, surface, startupMode: settings.startupMode, opacity: settings.opacity, autostart: settings.autostart,
    widgetSpan: settings.widgetSpan, widgetSide: settings.widgetSide,
    desktopAvailable: process.platform === 'win32',
    notificationsSupported: Notification.isSupported(), shortcutRegistered,
    desktopHost, lastError,
  };
}

function broadcastSettings() {
  for (const window of [mainWindow, desktopWindow]) {
    if (window && !window.isDestroyed() && !window.webContents.isDestroyed()) {
      window.webContents.send('desktop:mode-changed', snapshot(window === desktopWindow ? 'desktop' : 'app'));
    }
  }
  refreshTrayMenu();
}

function saveSettings(next = settings) {
  writeJson(settingsFile, next);
  settings = next;
}

function secureContents(window) {
  window.setMenu(null);
  window.webContents.setWindowOpenHandler(() => ({ action: 'deny' }));
  window.webContents.on('will-navigate', (event, url) => {
    let allowed = false;
    try { allowed = developmentUrl ? new URL(url).origin === new URL(developmentUrl).origin : url.split('#')[0].split('?')[0] === entryUrl; } catch { }
    if (!allowed) event.preventDefault();
  });
  window.webContents.on('will-attach-webview', (event) => event.preventDefault());
  window.webContents.session.setPermissionRequestHandler((_contents, _permission, callback) => callback(false));
  window.webContents.session.setPermissionCheckHandler(() => false);
}

function loadSurface(window, hash) {
  if (developmentUrl) {
    const url = new URL(developmentUrl);
    if (hash) url.hash = hash;
    return window.loadURL(url.href);
  }
  return window.loadFile(entryFile, hash ? { hash } : undefined);
}

function normalWindow() {
  if (!mainWindow || mainWindow.isDestroyed()) return;
  if (smokeTest) return;
  mainWindow.setSkipTaskbar(false);
  mainWindow.setAlwaysOnTop(false);
  mainWindow.setFullScreen(false);
  mainWindow.setOpacity(1);
  if (mainWindow.isMinimized()) mainWindow.restore();
  mainWindow.maximize();
  mainWindow.show();
  mainWindow.focus();
}

function cellEditorBounds() {
  const work = screen.getPrimaryDisplay().workArea;
  const anchor = cellEditorAnchor;
  const width = Math.min(work.width, Math.max(CELL_EDITOR_MIN_WIDTH, Math.round(anchor.width)));
  const height = Math.min(work.height, cellEditorExpanded ? CELL_EDITOR_EXPANDED_HEIGHT : CELL_EDITOR_COMPACT_HEIGHT);
  const x = Math.max(work.x, Math.min(work.x + Math.round(anchor.x), work.x + work.width - width));
  const y = Math.max(work.y, Math.min(work.y + Math.round(anchor.y), work.y + work.height - height));
  return { x, y, width, height };
}

function ensureCellEditor() {
  if (cellEditorWindow && !cellEditorWindow.isDestroyed() && cellEditorLoading) return cellEditorLoading;
  const editor = new BrowserWindow({
    title: CELL_EDITOR_TITLE, x: 0, y: 0, width: 240, height: CELL_EDITOR_COMPACT_HEIGHT,
    minWidth: CELL_EDITOR_MIN_WIDTH, minHeight: 96, frame: false, resizable: false, maximizable: false, minimizable: false,
    skipTaskbar: true, hasShadow: false, backgroundColor: '#1c3448', show: false, autoHideMenuBar: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'), contextIsolation: true,
      nodeIntegration: false, sandbox: true, webSecurity: true,
      allowRunningInsecureContent: false, webviewTag: false,
      // The window waits hidden between edits and must answer immediately.
      backgroundThrottling: false,
    },
  });
  cellEditorWindow = editor;
  editorWindows.add(editor);
  secureContents(editor);
  editor.on('close', (event) => {
    if (quitting || recreating) return;
    event.preventDefault();
    hideCellEditor();
  });
  editor.on('closed', () => {
    editorWindows.delete(editor);
    if (cellEditorWindow === editor) {
      cellEditorWindow = null;
      cellEditorLoading = null;
      cellEditorRevealPending = false;
      clearTimeout(cellEditorRevealTimer);
      cellEditorRevealTimer = null;
    }
  });
  // Clicking anywhere outside the cell finishes the edit, like a calendar list app.
  editor.on('blur', () => {
    if (!editor.isDestroyed() && editor.isVisible()) editor.webContents.send('desktop:cell-editor-blur');
  });
  editor.webContents.on('render-process-gone', () => {
    // Recreated on the next double-click; never leave a dead overlay on screen.
    if (!editor.isDestroyed()) editor.destroy();
    resetDesktopPointer();
  });
  cellEditorLoading = loadSurface(editor, 'cell-editor').then(() => editor, (error) => {
    if (!editor.isDestroyed()) editor.destroy();
    throw error;
  });
  return cellEditorLoading;
}

function revealCellEditor() {
  clearTimeout(cellEditorRevealTimer);
  cellEditorRevealTimer = null;
  if (!cellEditorRevealPending) return;
  cellEditorRevealPending = false;
  const editor = cellEditorWindow;
  if (smokeTest || !editor || editor.isDestroyed()) return;
  resetDesktopPointer();
  editor.show();
  editor.focus();
}

function hideCellEditor() {
  cellEditorRevealPending = false;
  clearTimeout(cellEditorRevealTimer);
  cellEditorRevealTimer = null;
  if (cellEditorWindow && !cellEditorWindow.isDestroyed() && cellEditorWindow.isVisible()) cellEditorWindow.hide();
  resetDesktopPointer();
}

function destroyCellEditor() {
  const editor = cellEditorWindow;
  cellEditorWindow = null;
  cellEditorLoading = null;
  cellEditorRevealPending = false;
  clearTimeout(cellEditorRevealTimer);
  cellEditorRevealTimer = null;
  if (editor && !editor.isDestroyed()) editor.destroy();
}

function prewarmCellEditor() {
  if (smokeTest || process.platform !== 'win32') return;
  void ensureCellEditor().catch(() => { /* retried on the next double-click */ });
}

async function recreateNormalWindow(reason) {
  // Destroy only our own widget HWND if shell/DPI changes prevent clean detach.
  // The management window and Chromium's persistent data remain untouched.
  recreating = true;
  destroyCellEditor();
  const previous = desktopWindow;
  desktopWindow = null;
  nativeState = null;
  desktopHost = null;
  calendarInteractive = false;
  mode = 'window';
  lastError = reason;
  if (previous && !previous.isDestroyed()) previous.destroy();
  try { await createWindow(); } finally { recreating = false; }
  broadcastSettings();
}

async function leaveDesktop() {
  if (!desktopWindow && !nativeState) return;
  try {
    if (nativeState) await callDesktopHelper('detach', nativeState);
    recreating = true;
    destroyCellEditor();
    const previous = desktopWindow;
    desktopWindow = null;
    nativeState = null;
    desktopHost = null;
    calendarInteractive = false;
    mode = 'window';
    if (previous && !previous.isDestroyed()) previous.destroy();
    recreating = false;
  } catch (error) {
    await recreateNormalWindow(`桌面模式恢复时遇到兼容性问题，已重新打开窗口。${errorMessage(error)}`);
  }
}

async function changeMode(next, { persist = true } = {}) {
  if (!['window', 'desktop', 'fullscreen'].includes(next)) return { ok: false, ...snapshot(), error: '未知的窗口模式。' };
  if (smokeTest && next !== 'window') return { ok: false, ...snapshot(), error: '隐藏测试环境禁止修改桌面模式。' };
  try {
    lastError = null;
    if (next === 'desktop') {
      if (process.platform !== 'win32') throw new Error('桌面常驻模式目前仅支持 Windows。');
      if (!nativeState || !desktopWindow || desktopWindow.isDestroyed()) {
        await createWindow({ show: false, surface: 'desktop' });
        try {
          const result = await callDesktopHelper('attach', null, widgetRect());
          nativeState = result.state;
          desktopHost = result.host;
          calendarInteractive = true;
          setCalendarInteractive(false);
          desktopWindow.setSkipTaskbar(true);
          mode = 'desktop';
        } catch (error) {
          await recreateNormalWindow(`桌面日历连接失败，已打开管理窗口。${errorMessage(error)}`);
          throw error;
        }
      }
      desktopWindow.showInactive();
      prewarmCellEditor();
    } else {
      await leaveDesktop();
      await createWindow({ show: false });
      if (next === 'fullscreen') {
        mainWindow.setSkipTaskbar(false);
        mainWindow.setAlwaysOnTop(false);
        mainWindow.setOpacity(1);
        mainWindow.setFullScreen(true);
        mainWindow.show();
        mainWindow.focus();
      } else normalWindow();
      mode = next;
    }
    if (persist && !smokeTest) saveSettings({ ...settings, startupMode: resolveStartupMode(next) });
    broadcastSettings();
    return { ok: true, ...snapshot() };
  } catch (error) {
    if (desktopDiagnostic) console.error('Desktop diagnostic:', errorMessage(error));
    lastError = next === 'desktop' && mode !== 'desktop' ? `桌面日历连接失败，已打开管理窗口。${errorMessage(error)}` : errorMessage(error);
    if (next === 'desktop' && mode !== 'desktop') { mode = 'window'; await createWindow(); normalWindow(); }
    broadcastSettings();
    return { ok: false, ...snapshot(), error: lastError };
  }
}

function queueMode(next, options) {
  const operation = modeQueue.then(() => changeMode(next, options));
  modeQueue = operation.catch(() => {});
  return operation;
}

function queueWidgetLayout(changes) {
  const operation = modeQueue.then(async () => {
    const previous = settings;
    const candidate = { ...settings, ...changes };
    try {
      if (nativeState && desktopWindow && !desktopWindow.isDestroyed()) {
        await callDesktopHelper('place', null, widgetRect());
      }
      saveSettings(candidate);
      broadcastSettings();
      return { ok: true, ...snapshot() };
    } catch (error) {
      if (nativeState && desktopWindow && !desktopWindow.isDestroyed()) {
        try { await callDesktopHelper('place', null, widgetRect()); } catch { /* retain original error */ }
      }
      return { ok: false, ...snapshot(), error: errorMessage(error) };
    }
  });
  modeQueue = operation.catch(() => {});
  return operation;
}

async function showWindow() {
  // Opening management is independent of the desktop calendar; it must neither
  // detach the widget nor change the user's next-launch preference.
  await modeQueue;
  await createWindow({ show: false });
  hideCellEditor();
  normalWindow();
  return { ok: true, ...snapshot('app') };
}

function validateEditorRequest(request) {
  if (!request || typeof request !== 'object' || Array.isArray(request)) throw new Error('编辑日程请求无效。');
  const { taskId, date, time } = request;
  if (taskId !== undefined && (typeof taskId !== 'string' || taskId.length < 1 || taskId.length > 200 || /[\u0000-\u001f]/.test(taskId))) throw new Error('日程编号无效。');
  if (typeof date !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(date)) throw new Error('日程日期无效。');
  if (time !== undefined && (typeof time !== 'string' || (time !== '' && !/^([01]\d|2[0-3]):[0-5]\d$/.test(time)))) throw new Error('日程时间无效。');
  return { taskId, date, time };
}

async function openCellEditor(request, inlineRect) {
  const { taskId, date, time } = validateEditorRequest(request);
  if (!smokeTest && (!desktopWindow || desktopWindow.isDestroyed() || !nativeState)) throw new Error('桌面日历尚未准备好。');
  if (!inlineRect || typeof inlineRect !== 'object' || !['x', 'y', 'width', 'height'].every(key => typeof inlineRect[key] === 'number' && Number.isFinite(inlineRect[key]))) throw new Error('日期格位置无效。');
  cellEditorAnchor = { x: inlineRect.x, y: inlineRect.y, width: inlineRect.width, height: inlineRect.height };
  cellEditorExpanded = false;
  const editor = await ensureCellEditor();
  if (editor.isDestroyed()) throw new Error('格内编辑暂时不可用，请再双击一次。');
  // Moving to another cell keeps text typed in a visible editor; an editor that
  // was dismissed (Alt+F4, management window) discards its leftover draft.
  const keepDraft = editor.isVisible();
  const seq = ++cellEditorSeq;
  editor.setBounds(cellEditorBounds());
  editor.webContents.send('desktop:cell-editor-open', { taskId: taskId || '', date, time: time || '', keepDraft, seq });
  // Reveal once the page has drawn the requested task; the timer only guards
  // against a renderer that never answers.
  cellEditorRevealPending = true;
  clearTimeout(cellEditorRevealTimer);
  cellEditorRevealTimer = setTimeout(revealCellEditor, 400);
  return { ok: true, ...snapshot('editor') };
}

async function openEditor(request) {
  const { taskId, date, time } = validateEditorRequest(request);
  const params = new URLSearchParams({ date });
  if (taskId) params.set('taskId', taskId);
  if (time) params.set('time', time);
  const editor = new BrowserWindow({
    title: '昱时 · 编辑日程',
    width: 660, height: 700, minWidth: 560, minHeight: 440, backgroundColor: '#f7f8fb',
    show: false, autoHideMenuBar: true, icon: appIconPath,
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'), contextIsolation: true,
      nodeIntegration: false, sandbox: true, webSecurity: true,
      allowRunningInsecureContent: false, webviewTag: false,
    },
  });
  editorWindows.add(editor);
  editor.on('closed', () => { editorWindows.delete(editor); });
  secureContents(editor);
  try {
    await loadSurface(editor, `editor?${params}`);
    if (!smokeTest) {
      setCalendarInteractive(false);
      editor.show();
      editor.focus();
    }
    return { ok: true, ...snapshot('editor') };
  } catch (error) {
    editor.destroy();
    throw error;
  }
}

function showNotification(value) {
  const options = validateNotification(value);
  if (smokeTest) return { ok: false, error: '隐藏测试环境禁止显示系统通知。' };
  if (!Notification.isSupported()) return { ok: false, error: '此系统暂不支持原生通知。' };
  const notification = new Notification({ ...options, silent: false, timeoutType: 'default' });
  visibleNotifications.add(notification);
  notification.on('click', () => { void showWindow(); });
  notification.on('close', () => visibleNotifications.delete(notification));
  notification.on('failed', (_event, failure) => {
    visibleNotifications.delete(notification);
    lastError = `系统未能显示通知：${errorMessage(failure)}`;
    broadcastSettings();
  });
  notification.show();
  // Keep a bounded set even when a platform does not emit a close event.
  if (visibleNotifications.size > 30) visibleNotifications.delete(visibleNotifications.values().next().value);
  return { ok: true };
}

function ensureReminderWindow() {
  if (reminderWindow && !reminderWindow.isDestroyed() && reminderLoading) return reminderLoading;
  const popup = new BrowserWindow({
    title: '昱时 · 提醒', width: 340, height: 120, frame: false, resizable: false, minimizable: false, maximizable: false,
    fullscreenable: false, skipTaskbar: true, alwaysOnTop: true, show: false, backgroundColor: '#1c3448', autoHideMenuBar: true,
    webPreferences: {
      preload: path.join(__dirname, 'reminder-preload.cjs'), contextIsolation: true,
      nodeIntegration: false, sandbox: true, webSecurity: true,
      allowRunningInsecureContent: false, webviewTag: false, backgroundThrottling: false,
    },
  });
  reminderWindow = popup;
  popup.setMenu(null);
  popup.webContents.setWindowOpenHandler(() => ({ action: 'deny' }));
  popup.webContents.on('will-navigate', (event) => event.preventDefault());
  popup.webContents.on('will-attach-webview', (event) => event.preventDefault());
  popup.webContents.session.setPermissionRequestHandler((_contents, _permission, callback) => callback(false));
  popup.on('close', (event) => {
    if (quitting) return;
    event.preventDefault();
    reminderShown = [];
    popup.hide();
  });
  popup.on('closed', () => { if (reminderWindow === popup) { reminderWindow = null; reminderLoading = null; } });
  reminderLoading = popup.loadFile(reminderFile).then(() => popup, (error) => {
    if (!popup.isDestroyed()) popup.destroy();
    throw error;
  });
  return reminderLoading;
}

function refreshReminderPopup() {
  const popup = reminderWindow;
  if (!popup || popup.isDestroyed()) return;
  if (!reminderShown.length) { popup.hide(); return; }
  const work = screen.getPrimaryDisplay().workArea;
  const width = 340;
  const height = Math.min(work.height, 22 + reminderShown.length * 104);
  popup.setBounds({ x: work.x + work.width - width - 16, y: work.y + work.height - height - 16, width, height });
  popup.webContents.send('reminder:items', reminderShown.map(({ key, title, body }) => ({ key, title, body })));
  popup.setAlwaysOnTop(true, 'screen-saver');
  // Never steal the keyboard from what the user is typing.
  popup.showInactive();
}

function showReminderPopup(due) {
  for (const item of due) {
    const key = JSON.stringify([item.id, item.at]);
    if (reminderShown.some(shown => shown.key === key)) continue;
    reminderShown.push({ key, id: item.id, title: item.title, body: item.late ? `错过的提醒 · ${item.body}` : item.body });
  }
  reminderShown = reminderShown.slice(-6);
  shell?.beep?.();
  void ensureReminderWindow().then(refreshReminderPopup).catch((error) => {
    // Fall back to system notifications when the popup cannot load.
    for (const item of reminderShown.splice(0)) showNotification({ title: item.title, body: item.body });
    lastError = `提醒弹窗未能显示：${errorMessage(error)}`;
    broadcastSettings();
  });
}

function deliverReminders() {
  if (!reminders) return;
  try {
    const due = reminders.takeDue();
    if (!due.length) return;
    if (process.platform === 'win32' && !smokeTest) { showReminderPopup(due); return; }
    if (!Notification.isSupported()) return;
    for (const reminder of due) {
      showNotification({ title: reminder.title, body: reminder.late ? `错过的提醒 · ${reminder.body}` : reminder.body });
    }
  } catch (error) {
    lastError = `提醒暂时不可用：${errorMessage(error)}`;
    broadcastSettings();
  }
}

function isTrustedFrame(event) {
  const window = [mainWindow, desktopWindow, ...editorWindows].find(candidate => candidate && !candidate.isDestroyed() && event.sender === candidate.webContents);
  if (!window || event.senderFrame !== window.webContents.mainFrame) return false;
  const url = event.senderFrame.url;
  return developmentUrl ? new URL(url).origin === new URL(developmentUrl).origin : url.split('#')[0].split('?')[0] === entryUrl;
}

function fromCellEditor(event) {
  return isTrustedFrame(event) && !!cellEditorWindow && !cellEditorWindow.isDestroyed() && event.sender === cellEditorWindow.webContents;
}

function registerIpc() {
  function handle(channel, action) {
    ipcMain.handle(channel, async (event, ...args) => {
      try {
        if (!isTrustedFrame(event)) throw new Error('此页面不能调用桌面功能。');
        const result = await action(...args);
        return { ...result, surface: event.sender === desktopWindow?.webContents ? 'desktop' : 'app' };
      } catch (error) { return { ok: false, ...snapshot(), error: errorMessage(error) }; }
    });
  }
  handle('desktop:get-settings', () => snapshot());
  handle('desktop:set-mode', (value) => queueMode(value));
  handle('desktop:set-widget-span', (value) => {
    if (!['week', 'twoWeeks', 'month'].includes(value)) throw new Error('未知的桌面日历范围。');
    return queueWidgetLayout({ widgetSpan: value });
  });
  handle('desktop:set-widget-side', (value) => {
    if (!['left', 'right'].includes(value)) throw new Error('未知的桌面日历位置。');
    return queueWidgetLayout({ widgetSide: value });
  });
  ipcMain.handle('desktop:set-calendar-interactive', async (event, value) => {
    if (!isTrustedFrame(event) || event.sender !== desktopWindow?.webContents || typeof value !== 'boolean')
      return { ok: false, error: '只有桌面日历可以设置鼠标交互区域。' };
    return { ok: setCalendarInteractive(value) };
  });
  ipcMain.handle('desktop:pass-context-menu', async (event) => {
    if (!isTrustedFrame(event) || event.sender !== desktopWindow?.webContents || !nativeState)
      return { ok: false, error: '只有桌面日历可以转交右键。' };
    try {
      setCalendarInteractive(false);
      await new Promise(resolve => setTimeout(resolve, 30));
      await callDesktopHelper('contextmenu');
      return { ok: true };
    } catch (error) {
      return { ok: false, error: errorMessage(error) };
    }
  });
  handle('desktop:open-editor', (request) => openEditor(request));
  ipcMain.handle('desktop:open-inline-editor', async (event, request) => {
    const testSurface = smokeTest && event.sender === mainWindow?.webContents && event.sender.getURL().endsWith('#desktop');
    if (!isTrustedFrame(event) || (event.sender !== desktopWindow?.webContents && !testSurface))
      return { ok: false, error: '只有桌面日历可以在日期格内编辑。' };
    try {
      if (!request || typeof request !== 'object' || !request.rect || typeof request.rect !== 'object') throw new Error('编辑日程请求无效。');
      return await openCellEditor(request, request.rect);
    } catch (error) { return { ok: false, error: errorMessage(error) }; }
  });
  ipcMain.handle('desktop:cell-editor-ready', async (event) => {
    if (!fromCellEditor(event)) return { ok: false, error: '当前不是格内编辑。' };
    revealCellEditor();
    return { ok: true };
  });
  ipcMain.handle('desktop:resize-cell-editor', async (event, expanded) => {
    if (!fromCellEditor(event) || typeof expanded !== 'boolean') return { ok: false, error: '当前不是格内编辑。' };
    cellEditorExpanded = expanded;
    if (cellEditorAnchor) cellEditorWindow.setBounds(cellEditorBounds());
    return { ok: true };
  });
  ipcMain.handle('desktop:close-editor', async (event, seq) => {
    if (!isTrustedFrame(event)) return { ok: false, error: '此页面不能关闭编辑窗口。' };
    const editor = BrowserWindow.fromWebContents(event.sender);
    if (!editorWindows.has(editor)) return { ok: false, error: '当前不是编辑窗口。' };
    if (editor === cellEditorWindow) {
      // A click-away that finishes after the next double-click must not hide the new date.
      if (typeof seq === 'number' && seq !== cellEditorSeq) return { ok: true, stale: true };
      hideCellEditor();
    } else editor.close();
    return { ok: true };
  });
  ipcMain.handle('reminder:act', async (event, key, action) => {
    const popup = reminderWindow;
    if (!popup || popup.isDestroyed() || event.sender !== popup.webContents || event.senderFrame !== popup.webContents.mainFrame
      || event.senderFrame.url !== reminderUrl || typeof key !== 'string' || !['snooze', 'dismiss'].includes(action))
      return { ok: false, error: '无效的提醒操作。' };
    const item = reminderShown.find(shown => shown.key === key);
    if (!item) return { ok: false, error: '这条提醒已处理。' };
    try {
      if (action === 'snooze') reminders.snooze(item, Date.now() + SNOOZE_MINUTES * 60_000);
    } catch (error) { return { ok: false, error: errorMessage(error) }; }
    reminderShown = reminderShown.filter(shown => shown !== item);
    refreshReminderPopup();
    return { ok: true };
  });
  handle('desktop:show-window', () => showWindow());
  handle('desktop:set-opacity', (value) => {
    if (typeof value !== 'number' || !Number.isFinite(value) || value < 0.35 || value > 1) throw new Error('不透明度须介于 0.35 和 1 之间。');
    if (desktopWindow && !desktopWindow.isDestroyed()) desktopWindow.setOpacity(value);
    try { saveSettings({ ...settings, opacity: value }); } catch (error) { if (desktopWindow && !desktopWindow.isDestroyed()) desktopWindow.setOpacity(settings.opacity); throw error; }
    broadcastSettings();
    return { ok: true, ...snapshot() };
  });
  handle('desktop:set-autostart', (value) => {
    if (typeof value !== 'boolean') throw new Error('开机启动设置无效。');
    if (!app.isPackaged || !loginItemSupported) throw new Error('请在打包后的应用中设置开机启动。');
    const executable = process.env.PORTABLE_EXECUTABLE_FILE || process.execPath;
    const previous = settings.autostart;
    app.setLoginItemSettings({ openAtLogin: value, path: executable, args: ['--autostart'] });
    try { saveSettings({ ...settings, autostart: value }); } catch (error) {
      app.setLoginItemSettings({ openAtLogin: previous, path: executable, args: ['--autostart'] });
      throw error;
    }
    broadcastSettings();
    return { ok: true, ...snapshot() };
  });
  handle('desktop:notify', (value) => {
    validateNotification(value);
    if (Date.now() - lastImmediateNotification < 1500) throw new Error('提醒发送过快，请稍后再试。');
    lastImmediateNotification = Date.now();
    return showNotification(value);
  });
  handle('desktop:sync-reminders', (values) => {
    const count = reminders.sync(values);
    deliverReminders();
    return { ok: true, count };
  });
}

function trayIcon() {
  if (process.platform === 'darwin' && typeof nativeImage.createFromPath === 'function') {
    // Menu bar icons are ~18pt.
    const icon = nativeImage.createFromPath(path.join(__dirname, 'icon-32.png'));
    if (!icon.isEmpty()) return icon.resize({ width: 18, height: 18 });
  }
  const icon = typeof nativeImage.createFromPath === 'function' ? nativeImage.createFromPath(appIconPath) : null;
  return icon && !icon.isEmpty() ? icon : makeTrayIcon();
}

function makeTrayIcon() {
  // Generated RGBA icon, so packaging does not depend on an external image file.
  const width = 32;
  const bitmap = Buffer.alloc(width * width * 4);
  for (let y = 0; y < width; y++) for (let x = 0; x < width; x++) {
    const offset = (y * width + x) * 4;
    const inside = x >= 3 && x < 29 && y >= 3 && y < 29;
    const white = inside && ((y >= 9 && y < 12) || (x >= 9 && x < 13 && y >= 16 && y < 21) || (x >= 19 && x < 23 && y >= 16 && y < 21));
    bitmap[offset] = white ? 246 : 79; // nativeImage bitmap uses BGRA on Windows.
    bitmap[offset + 1] = white ? 249 : 117;
    bitmap[offset + 2] = white ? 247 : 48;
    bitmap[offset + 3] = inside ? 255 : 0;
  }
  return nativeImage.createFromBitmap(bitmap, { width, height: width, scaleFactor: 1 });
}

function refreshTrayMenu() {
  if (!tray) return;
  tray.setContextMenu(Menu.buildFromTemplate([
    { label: process.platform === 'darwin' ? '打开管理窗口  ⌥⌘D' : '打开管理窗口  Ctrl+Alt+D', click: () => { void showWindow(); } },
    { label: '常驻桌面（主屏）', type: 'checkbox', checked: mode === 'desktop', enabled: process.platform === 'win32', click: () => { void queueMode(mode === 'desktop' ? 'window' : 'desktop'); } },
    { type: 'separator' },
    { label: '退出昱时（停止提醒）', click: () => { void quitApplication(); } },
  ]));
}

// The portable EXE has no installer, so Windows search only finds it through a
// Start menu shortcut. Keep that shortcut and the login item pointing at the EXE
// the user launched, and turn launch-at-login on once by default (the user asked
// for both on 2026-09-28; 设置 → 开机启动 can still turn it off).
function integrateWithWindows() {
  if (!app.isPackaged || process.platform !== 'win32' || smokeTest) return;
  const executable = process.env.PORTABLE_EXECUTABLE_FILE || process.execPath;
  try {
    const shortcut = path.join(app.getPath('appData'), 'Microsoft', 'Windows', 'Start Menu', 'Programs', '昱时.lnk');
    let current = null;
    try { current = shell.readShortcutLink(shortcut).target; } catch { /* missing or unreadable: recreate */ }
    if (current !== executable) {
      shell.writeShortcutLink(shortcut, 'replace', {
        target: executable, description: '昱时 · 桌面日历与清单', icon: executable, iconIndex: 0, appUserModelId: 'app.shiri.calendar',
      });
    }
  } catch (error) { lastError = `开始菜单快捷方式未能创建：${errorMessage(error)}`; }
  try {
    const next = { ...settings };
    if (!settings.autostartDefaulted) { next.autostart = true; next.autostartDefaulted = true; }
    if (next.autostart) app.setLoginItemSettings({ openAtLogin: true, path: executable, args: ['--autostart'] });
    if (next.autostart !== settings.autostart || next.autostartDefaulted !== settings.autostartDefaulted) saveSettings(next);
  } catch (error) { lastError = `开机启动未能设置：${errorMessage(error)}`; }
  broadcastSettings();
}

// macOS counterpart: no Start menu, but launch-at-login is defaulted on once the
// same way (System Settings → 登录项, or 设置 → 开机启动, can turn it off).
function integrateWithMac() {
  if (!app.isPackaged || process.platform !== 'darwin' || smokeTest) return;
  try {
    const next = { ...settings };
    if (!settings.autostartDefaulted) { next.autostart = true; next.autostartDefaulted = true; }
    if (next.autostart) app.setLoginItemSettings({ openAtLogin: true });
    if (next.autostart !== settings.autostart || next.autostartDefaulted !== settings.autostartDefaulted) saveSettings(next);
  } catch (error) { lastError = `开机启动未能设置：${errorMessage(error)}`; }
  broadcastSettings();
}

async function quitApplication() {
  if (quitting) return;
  await modeQueue;
  await leaveDesktop();
  quitting = true;
  app.quit();
}

async function createWindow({ show = true, surface = 'app' } = {}) {
  const isWidget = surface === 'desktop';
  const existing = isWidget ? desktopWindow : mainWindow;
  if (existing && !existing.isDestroyed()) {
    if (show && !isWidget) normalWindow();
    return existing;
  }
  const work = screen.getPrimaryDisplay().workAreaSize;
  const window = new BrowserWindow({
    title: isWidget ? '昱时 · 桌面日历' : '昱时 · 日程管理',
    width: Math.min(1440, work.width), height: Math.min(960, work.height),
    minWidth: isWidget ? 560 : 760, minHeight: isWidget ? 240 : 560, show: false,
    backgroundColor: isWidget ? '#00000000' : '#f7f8f5',
    ...(isWidget ? { frame: false, transparent: true, hasShadow: false, skipTaskbar: true } : {}),
    autoHideMenuBar: true, icon: appIconPath,
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true, nodeIntegration: false, sandbox: true,
      webSecurity: true, allowRunningInsecureContent: false, webviewTag: false,
      ...(smokeTest ? { offscreen: true, backgroundThrottling: false } : {}),
    },
  });
  if (isWidget) desktopWindow = window;
  else mainWindow = window;
  secureContents(window);
  window.setOpacity(isWidget ? settings.opacity : 1);
  window.on('close', (event) => {
    if (quitting || recreating) return;
    event.preventDefault();
    if (isWidget) void queueMode('window');
    else window.hide();
  });
  window.on('closed', () => {
    if (mainWindow === window) mainWindow = null;
    if (desktopWindow === window) desktopWindow = null;
    if (isWidget && !quitting && !recreating && nativeState) {
      destroyCellEditor();
      nativeState = null;
      desktopHost = null;
      mode = 'window';
      lastError = '桌面环境已变化，已打开日程管理窗口。';
      void createWindow().catch((error) => { lastError = errorMessage(error); });
    }
  });
  window.on('query-session-end', () => { quitting = true; });
  window.webContents.on('did-finish-load', () => broadcastSettings());
  window.webContents.on('render-process-gone', () => {
    if (!quitting && !window.isDestroyed()) {
      lastError = '页面发生异常，正在重新载入；可从托盘打开管理窗口。';
      window.webContents.reload();
    }
  });
  await loadSurface(window, isWidget ? 'desktop' : '');
  if (!window.isDestroyed() && !smokeTest && show && !isWidget) normalWindow();
  return window;
}

async function showLaunchSurface() {
  const result = await queueMode(settings.startupMode, { persist: false });
  // Launching the EXE again should reveal the calendar even if management was
  // left open in the already-running process. Keep the manager available from
  // the widget, tray and shortcut.
  if (result.ok && result.mode === 'desktop' && mainWindow && !mainWindow.isDestroyed()) mainWindow.hide();
  return result;
}

if (hasLock) {
  app.on('second-instance', () => { void app.whenReady().then(showLaunchSurface); });
  app.on('activate', () => { void showWindow(); });
  app.on('window-all-closed', () => { /* Main process and reminders stay in the tray. */ });
  app.on('before-quit', (event) => {
    if (!quitting && nativeState) {
      event.preventDefault();
      void quitApplication();
    } else quitting = true;
  });
  app.on('will-quit', () => {
    if (reminderTimer) clearInterval(reminderTimer);
    globalShortcut.unregisterAll();
    tray?.destroy();
  });
  app.whenReady().then(async () => {
    settingsFile = path.join(app.getPath('userData'), 'desktop-settings.json');
    const saved = readJson(settingsFile, {}) || {};
    settings.opacity = typeof saved.opacity === 'number' && saved.opacity >= 0.35 && saved.opacity <= 1 ? saved.opacity : 1;
    settings.autostart = saved.autostart === true;
    settings.autostartDefaulted = saved.autostartDefaulted === true;
    settings.startupMode = resolveStartupMode(saved.startupMode);
    settings.widgetSpan = ['week', 'twoWeeks', 'month'].includes(saved.widgetSpan) ? saved.widgetSpan : 'twoWeeks';
    settings.widgetSide = ['left', 'right'].includes(saved.widgetSide) ? saved.widgetSide : 'right';
    reminders = new ReminderStore(path.join(app.getPath('userData'), 'scheduled-reminders.json'));
    registerIpc();
    if (!smokeTest) {
      tray = new Tray(trayIcon());
      tray.setToolTip('昱时 · 日历与清单');
      tray.on('double-click', () => { void showWindow(); });
      shortcutRegistered = globalShortcut.register('CommandOrControl+Alt+D', () => { void showWindow(); });
      refreshTrayMenu();
      reminderTimer = setInterval(deliverReminders, 15_000);
      powerMonitor.on('resume', deliverReminders);
      powerMonitor.on('unlock-screen', deliverReminders);
    }
    // Load invisibly, then attach/apply the preferred mode before first display.
    // Recovery recreations use createWindow() directly and never retry attachment.
    await showLaunchSurface();
    if (!smokeTest) deliverReminders();
    integrateWithWindows();
    integrateWithMac();
  }).catch((error) => {
    console.error('昱时启动失败：', errorMessage(error));
    quitting = true;
    app.quit();
  });
}

module.exports = { resolveStartupMode };
